- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME')}}/.ssh/id_rsa"
  pre_tasks:
    - name: Update the package list
      tags: always
      apt:
        update_cache: yes
  tasks:
    - name: Install other packages - ripgrep, tree, fd-find, locales
      apt:
        name:
          - git
          - curl
          - ripgrep
          - tree
          - fd-find
          - locales
          - bc
          - coreutils
          - gawk
          - jq
          - playerctl
        state: latest
    - name: Install locale-gen en_US.UTF-8, locale-gen en_AU, locale-gen en_AU.UTF-8
      shell: |
        locale-gen en_US.UTF-8
        locale-gen en_AU
        locale-gen en_AU.UTF-8
    - include: task/zsh.yml
    - include: task/neovim.yml
    - include: task/python.yml
    - include: task/node.yml
    - include: task/ohmyposh.yml

    - name: Clone dotfiles repository
      git:
        repo: https://github.com/mkhai9x/tempdotfiles.git
        dest: ~/tempdotfiles

    - name: Copy .zshrc to home directory
      copy:
        src: "~/tempdotfiles/.zshrc"
        dest: "~/.zshrc"
        remote_src: yes

    - name: Create .config directory if it doesn't exist
      file:
        path: "~/.config"
        state: directory
        mode: "0755"
    - name: Copy other folders to .config directory
      copy:
        src: "~/tempdotfiles/"
        dest: "~/.config/"
        remote_src: yes
        directory_mode: yes
    - name: Install tmux
      apt:
        name: tmux
        state: present
        update_cache: yes
    - name: Ensure .ssh directory exists.
      become_user: root
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory
      tags:
        - dotfiles
    - name: Insall ssh key
        - ssh
